Multi Node jobs with Multi-Server
subhasisb/openpbs pull request #131
Opened 2020-08-17 19:10 UTC by nithinj

* Broadcasting qmgr commands to all servers
* Aggregating stat_nodes in the IFL layer
* Firing requests to multiple servers before starting to read their response

2020-08-18 07:49 UTC, subhasisb commented
So, understanding the design (aloud):

1. nodes need to be created on all servers and some flag needs to be used to tell owning server, that this is the owner. So you are handling this by adding the ND_ATR_at_server=pbs_server_name in the IS_REGISTERMOM handler at server. Sounds good! This way, all servers will have the node structure, but the mom knows to talk to ONLY one server, and that server is the owner of the mom.

2. This allows the node objects to be updated before/after job run to adjust resources on nodes (in MN case) where (some of) the nodes do not belong to the server which owns the job. However, to depict a correct allocation on the nodes, you have to aggregate the nodes from all the servers on the client side.

Two issues i can think of with this approach:
a) The scheduler has to "aggregate" node resources for all servers to know what is actually allocated (before scheduling). Does this amount to performance penalty? Even for single node/code jobs? Do we have to iterate over all nodes (say 60k nodes) 5 times to aggregate resources, even when the bulk of the jobs is short, single core HTC style jobs? 

b) What happens if a server is down? In the other approach, when a server is down, its "partition" is down - no jobs or nodes from it is used by the scheduler, but the scheduler can still go ahead. In this approach, however, we have incomplete data about nodes from the other servers. The scheduler probably should not use such nodes for any jobs? However, the same problem exists with other shared objects like queues and server where limits and resources assigned data is aggregated from multiple servers, so if a server is down, then the aggregate "resources used" on these "common objects" is incomplete, and so what should the scheduler do? Should it simply not schedule any more and wait for the server to come up on an alternate node?

About the qmgr commands reaching out to all servers, sounds fine, some thoughts for future:
We need to try to do a "best effort" but "not guaranteed" delivery to all server instances, as follows:
1. Qmgr must successfully connect to ALL server instances before it will proceed, else it fails
2. Qmgr operation must succeed on all server instances, else we rollback on all servers if any one fails.
3. If at the point of rollback another server dies, we emit message that the operation was "partial" and the cluster might have issues (is in inconsistent state), admins help required

2020-08-18 14:34 UTC, nithinj commented
@subhasisb ,

Sorry about not adding more details in the description earlier.

>Does this amount to performance penalty?


To avoid any performance penalty for a single HTC job, we have multiple optimizations in place. The server will not encode an alien node unless it is active (means jobs/resv running on it). This will eliminate the need for aggregation in case of single  core jobs. IFL layer also makes use of avl indexing to find the nodes faster, rather than looping through. This will help in a MN scenario. Although we have eliminated aggregation for HTC jobs, servers will still have to walk through all the nodes (not performing any operations, just checking flags, so not complicated). Firing requests to all servers before reading the response will help to avoid any slight delay occured at server side due to this.
I will have to do some performance tests to analyze this further.

> In this approach, however, we have incomplete data about nodes from the other servers.


When the partition is down, we cannot furnish the data about those nodes as the owning server is down. Other servers might furnish the data if those nodes has jobs running on them. But their state will be down so the scheduler cannot proceed to schedule jobs on them.
Those nodes which has MN jobs running on them on the server which has gone down will furnish partial data by their owning servers. This will definitely lead to oversubscription on those nodes. So the only option for the scheduler would be to wait for the server to come upon some other machine as you rightly said. But it can be a rare scenario and I will keep my faith in the pacemaker.
However, as you know scheduler will not rely on this in the longer term. With persistent scheduler this will only be serving pbsnodes.

> Qmgr must successfully connect to ALL server instances before it will proceed, else it fails

Sound good. I will address it as part of this PR.

> Qmgr operation must succeed on all server instances, else we rollback on all servers if any server fails.

We might need a separate commit message to be fired in that case. Will address it in the future. We can also think of handling in the client side by firing the reverse message (SET<->UNSET, CREATE<->DELETE). Commit looks cleaner to me.

2020-08-19 05:13 UTC, subhasisb commented
> We might need a separate commit message to be fired in that case. Will address it in the future. We can also think of handling in the client side by firing the reverse message (SET<->UNSET, CREATE<->DELETE). Commit looks cleaner to me.

Sure, commit is fine as well. To implement it correctly, usually u need "ready to commit" - see 2 phase commits in database distributed transactions. The alternate idea that databases use today is "compensating transactions" since 2-phase commits are expensive and still has issues. Anyways, these all for future. For now, we can simply show the admin an error if a server goes down in between, saying "hey we could only do partial updates, and server x failed in the process, so you might want to check it and update it manually"- that might be good enough for even the next 6 months. However, ensuring that we do not proceed until we can connect to all the servers is probably simple to do and inexpensive, and already provides for quite some robustness!

2020-08-19 05:18 UTC, subhasisb commented
About the scheduler side of aggregating:

1. For the node stat performance angle, after august (post poc), we should do a simple POC to check difference in implementation between aggregating nodes at scheduler/ifl vs "not-sharing" node structure between servers.

2. About the aggregate data of the common objects like server.resources_used and workq.resources_used and limits etc, I feel it is quite good and acceptable to "hang scheduling" till scheduler can connect with ALL the configured servers. What is the down side? Well, when a server fails, the scheduling will hang till the server comes up on another host. However, this is typically slow if the hardware actually failed (rare), and quite fast if it is a manually triggered failover (scheduled downtime). This means we need to make the "scheduler/manual failover" super-fast, which means our shutdown and server startup (with 1 million jobs) should still be quite fast.

2020-08-19 10:41 UTC, subhasisb approved these changes

2020-08-25 13:44 UTC, nithinj commented
@subhasisb ,

There is a catch in this approach. Vnodes structures has to be available in all servers for this to work. But vnodes are not only created using qmgr. It also gets created using mom when it sends an update2.

If all servers needs to have access to the structures, mom has to send update2 to every server. We can close this connection soon after we send an inventory. This happens only when mom's internal state changes. what do you think?

2020-08-26 14:21 UTC, nithinj commented
@subhasisb ,

I did end to end job run performance test of 10k single node jobs with 5 servers, 50 moms and 200 cpus on each of them. Daemons are launched using pbs_pocker script. The results looks encouraging.

With multi-node changes: 1303.75 jobs/sec
Without multi-node changes: 1244.71 jobs/sec

I'd attribute the increase in performance to parallel requests during stat.
A detailed report is attached for reference: 
[perf_results.txt](https://github.com/subhasisb/openpbs/files/5130406/perf_results.txt)

2020-08-27 03:50 UTC, suresh-thelkar commented on src/lib/Libifl/int_manager.c
> +	if ((pbs_verify_attributes(random_srv_conn(svr_connections), function,
When manager commands are issued from the external clients like qmgr, we should still support partial updates. In order to do that one of the things that we need to do is we should not quit if pbs_verifiy_attributes is failed on one of the servers that is chosen randomly, we actually need to try other servers and then proceed.

2020-08-27 03:56 UTC, suresh-thelkar requested changes

2020-08-27 03:56 UTC, suresh-thelkar commented on src/lib/Libifl/int_manager.c
> +		if (svr_connections[i].state != SVR_CONN_STATE_CONNECTED)
This function should remember the fact that one of the servers is down and should respond while sending the final return code.

2020-08-27 03:56 UTC, suresh-thelkar commented on src/lib/Libifl/pbsD_selectj.c
> +		if (svr_connections[i].state != SVR_CONN_STATE_CONNECTED)
Here also we should record the fact that one of the servers is down and when the function returns it has to send the right return code.

2020-08-27 04:31 UTC, subhasisb commented
> @subhasisb ,
> 
> I did end to end job run performance test of 10k single node jobs with 5 servers, 50 moms and 200 cpus on each of them. Daemons are launched using pbs_pocker script. The results looks encouraging.
> 
> With multi-node changes: 1303.75 jobs/sec
> Without multi-node changes: 1244.71 jobs/sec
> 
> I'd attribute the slight increase in performance to parallel requests during stat.
> A detailed report is attached for reference:
> [perf_results.txt](https://github.com/subhasisb/openpbs/files/5130406/perf_results.txt)

Sounds good. This means the

2020-08-27 04:35 UTC, subhasisb commented
> @subhasisb ,
> 
> I did end to end job run performance test of 10k single node jobs with 5 servers, 50 moms and 200 cpus on each of them. Daemons are launched using pbs_pocker script. The results looks encouraging.
> 
> With multi-node changes: 1303.75 jobs/sec
> Without multi-node changes: 1244.71 jobs/sec
> 
> I'd attribute the slight increase in performance to parallel requests during stat.
> A detailed report is attached for reference:
> [perf_results.txt](https://github.com/subhasisb/openpbs/files/5130406/perf_results.txt)

I suggest we now implement the "other" approach and see how easy/difficult the implementation would be

2020-08-27 05:29 UTC, subhasisb commented
Went over cursorily over the code changes in int_status.c. I think the aggregate_nodes() and the functions from there are still quite heavyweight and will show it's issues when we have a large number of nodes, say 100k or more. (our goal are exascale machines)

Consider this "fictitious" case: If we had 100k nodes, and assuming a site runs 10 servers to handle the load, we would have each server handling 10k nodes. When we do a node stat, we will have the following sequence:

1) statnode(server1) - 10k nodes returned, add to avltree (nothing to compare)
2) statnode(server2) - 10k nodes returned, so iterate 10k times over find_avltree(10k+ size)
3) statnode(server3) - 10k nodes returned, so iterate 10k times over find_avltree(20k+ size)
4) statnode(server4) - 10k nodes returned, so iterate 10k times over find_avltree(30k+ size)
..
..
..
10) statnode(server10) - 10k nodes returned, so iterate 10k times over find_avltree(90k+ size)

This complexity has to be borne even if the site is not running multinode jobs, right?

While avltree lookup is very fast, there is actually not need to incur this complexity.

Consider, now, the "other" approach:
1) Nodes are owned by only one server, so code is clean, no aggregation of node data anywhere (this is large in number, so it makes sense to not do it)
2) While we still have to aggregate for common objects servers, queues, etc, these common objects are much smaller in numbers, so aggregation is inexpensive.
3) We also do not anyway have to aggregate anything for jobs since the data for them will be reported by only one server anyway, so that large set of objects is out of the way anway.
4) The additional change that has to be done to send the amount of resources to "adjust" for a job that is does not own sounds simpler code anyway.

2020-08-27 13:58 UTC, nithinj commented
@subhasisb 
* Numbers: log2(10k) ~ 13 , log2(90k) ~ 16. So its a difference of 3 comparisons if avl tree is efficient.
* In a such large cluster, all other time are also going to exponentially increase. query time due to large no of jobs, and sched also has to do iterations and lookups are also more on a larger dataset. Time taken to do something is relative to other operations we do. What we see as a bottleneck in a miniature version will also be a bottleneck in an expanded cluster. but if they are not a bottleneck in a miniature version, that may not be a big reason to worry!

I'm free right now as this multi-node approach is complete at least in a POC point of view. I'll try the other approach and see.

* My major concern is that its a different design approach altogether. Its a separate code path. We will be having two different paths to test and maintain. aggregation (for queue and svr) peer svr update (for node)
* It does not looks as simpler as this. Let me list the things we need to do to achieve a well defined behaviour:


* The server need to broadcast the selectspec to all peer servers, as it does not know the owner of nodes. Other servers needs to parse and INCR/DECR only on nodes (this path covers queue and server today).
* Other servers has to read and parse the requests even if they dont have the nodes which targets the request. Quite wasteful.
* Server mainly need to send the requests mainly in three places - 1. when run requests receives. 2. obit/update comes 3. when server starts up.
* what if one of the servers are down? It has to wait till it comes up. Periodically check whether its up. Do not proceed with the requests (may be keep it in the memory) or reject and offload to another daemon (sched or mom). Cannot be offloaded when server comes up, so might have to code both.
* We might also need an ACK from server as the src server do not know whether operation has succeeded or not.
* In that case this might slow down multi-node jobs with multi-svr tremendously, so it has to be asynchronous. That will be more changes.

This is what I can think of. But we will discover more unknowns as we code like we did with vnode update in the aggregation approach.

2020-08-27 14:19 UTC, subhasisb commented
> @subhasisb
> 
>     * Numbers: log2(10k) ~ 13 , log2(90k) ~ 16. So its a difference of 3 comparisons if avl tree is efficient.
> 
>     * In a such large cluster, all other time are also going to exponentially increase. query time due to large no of jobs, and sched also has to do iterations and lookups are also more on a larger dataset. Time taken to do something is relative to other operations we do. What we see as a bottleneck in a miniature version will also be a bottleneck in an expanded cluster. but if they are not a bottleneck in a miniature version, that may not be a big reason to worry!
> 
> 
> I'm free right now as this multi-node approach is complete at least in a POC point of view. I'll try the other approach and see.
> 
>     * My major concern is that its a different design approach altogether. Its a separate code path. We will be having two different paths to test and maintain. aggregation (for queue and svr) peer svr update (for node)
> 
>     * It does not looks as simpler as this. Let me list the things we need to do to achieve a well defined behaviour:
> 
>     * The server need to broadcast the selectspec to all peer servers, as it does not know the owner of nodes. Other servers needs to parse and INCR/DECR only on nodes (this path covers queue and server today).
> 
>     * Other servers has to read and parse the requests even if they dont have the nodes which targets the request. Quite wasteful.
> 
>     * Server mainly need to send the requests mainly in three places - 1. when run requests receives. 2. obit/update comes 3. when server starts up.
> 
>     * what if one of the servers are down? It has to wait till it comes up. Periodically check whether its up. Do not proceed with the requests (may be keep it in the memory) or reject and offload to another daemon (sched or mom). Cannot be offloaded when server comes up, so might have to code both.
> 
>     * We might also need an ACK from server as the src server do not know whether operation has succeeded or not.
> 
>     * In that case this might slow down multi-node jobs with multi-svr tremendously, so it has to be asynchronous. That will be more changes.
> 
> 
> This is what I can think of. But we will discover more unknowns as we code like we did with vnode update in the aggregation approach.

Cool - let's try it. We need to complete that approach to decide between the two. Like i said, i agree that the avl lookup is quite fast, but if we do not need to do it, we do not need to do it - and that is the main argument, at this point, for the other approach. As you mentioned, only trying it will teach us what is amiss with the other approach. Besides that, I think we would not need the moms to connect to all the servers to update vnode stuff.

2020-08-27 15:48 UTC, nithinj commented
@subhasisb ,
The mom side is already coded. Its super simple. The failure cases are not handled in it. But making mom complex does not bother me as much as making the server complex.

Do you think it will be more efficient to work on node_stat_diff API so that scheduler can make use of it as soon as some basics of diff_stat is ready. All these server-side changes will only be helping pbsnodes in the future. I just want to make sure we are not overthinking on a rather useless module of tomorrow. If diff_stat was not in our horizon it makes perfect sense to find out the perfect approach and proceed with it. But otherwise, whatever we do is not going to stand after diff_stat.

2020-08-27 16:35 UTC, subhasisb commented
> @subhasisb ,
> The mom side is already coded. Its super simple. The failure cases are not handled in it. But making mom complex does not bother me as much as making the server complex.
> 
> Do you think it will be more efficient to work on node_stat_diff API so that scheduler can make use of it as soon as some basics of diff_stat is ready. All these server-side changes will only be helping pbsnodes in the future. I just want to make sure we are not overthinking on a rather useless module of tomorrow. If diff_stat was not in our horizon it makes perfect sense to find out the perfect approach and proceed with it. But otherwise, whatever we do is not going to stand after diff_stat.

No @nithinj I think we should try the simple side also and really:
1. I would really prefer that the moms do not know about other servers. This just brings in a lot of additional complexity, it is not a question of whether code is already done or not
2. diff_stat has nothing to do with this. It is way more complex than we are thinking it is.

2020-08-27 18:38 UTC, nithinj commented on src/lib/Libifl/int_manager.c
> +		if (svr_connections[i].state != SVR_CONN_STATE_CONNECTED)
I'll go ahead and raise as a seperate PR. I hope you are not working on the same.

2020-08-27 18:40 UTC, nithinj commented on src/lib/Libifl/pbsD_selectj.c
> +		if (svr_connections[i].state != SVR_CONN_STATE_CONNECTED)
Why do we do that inside status/select? It is decided at the time of connect() and the client has ignored that proceeded with the query.

2020-08-27 18:45 UTC, nithinj commented on src/lib/Libifl/int_manager.c
> +	if ((pbs_verify_attributes(random_srv_conn(svr_connections), function,
I think we should try the reverse. If it cannot succeed to make the change in all the servers, instances will be in conflicting states.

2020-08-28 10:40 UTC, suresh-thelkar commented on src/lib/Libifl/int_manager.c
> +	if ((pbs_verify_attributes(random_srv_conn(svr_connections), function,
Yes. I actually meant for stat requests. Even if one of the servers is down we should show partial stats.

2020-08-28 10:41 UTC, suresh-thelkar commented on src/lib/Libifl/int_manager.c
> +		if (svr_connections[i].state != SVR_CONN_STATE_CONNECTED)
I have actually made some similar changes in the following PR. Please go through it and give your suggestions.
https://github.com/subhasisb/openpbs/pull/135

2020-08-28 10:43 UTC, suresh-thelkar commented on src/lib/Libifl/pbsD_selectj.c
> +		if (svr_connections[i].state != SVR_CONN_STATE_CONNECTED)
This is because we should show whatever data is available as far as stats are concerned. I have done the mentioned changes in the following PR. Please go through it and provide your suggestions.
https://github.com/subhasisb/openpbs/pull/135

2020-08-28 12:19 UTC, nithinj commented on src/lib/Libifl/int_manager.c
> +	if ((pbs_verify_attributes(random_srv_conn(svr_connections), function,
random_srv_conn is getting you a server which already got connected.

2020-08-31 13:22 UTC, nithinj commented
@subhasisb 
> I would really prefer that the moms do not know about other servers.

Servers and all moms have to be connected by some means for multi-node jobs to work. So networking should be there.
If it is about, PBS server instances conf variable, that can be returned by the server it is contacting to.

2020-08-31 13:35 UTC, subhasisb commented
> @subhasisb
> 
> > I would really prefer that the moms do not know about other servers.
> 
> Servers and all moms have to be connected by some means for multi-node jobs to work. So networking should be there.
> If it is about, PBS server instances conf variable, that can be returned by the server it is contacting to.

TPP networking is different since it is just routing. I would like to avoid the case of the mom having to talk to multiple server. So let us just code the other approach, please - then we can decide. I think we are debating even before trying it out. For one, i think the other approach would be simple enough to code anyway. It would what we do when the MS tells the sister moms about a job - sort of like a join job. I can offer to help and code it myself

2020-08-31 14:06 UTC, nithinj commented
@subhasisb ,
I've started coding that. I was trying to conclude my thoughts. I do not have an overall picture in mind yet. We can discuss more on the call. I'll take a look at join_job.

2020-08-31 16:25 UTC, subhasisb commented
so one of the reasons also is that what happens when a client (not scheduler) does a pbsnode "single-node". The problem with the IFL aggregation is that now the client needs to pull a million jobs to know which ones are running on this single node

2020-08-31 17:35 UTC, nithinj commented
@subhasisb ,
not really. client does a single node stat on all servers and just aggregate the nodes in the receiving end. Jobs do not come into pitcure.

2020-09-01 02:16 UTC, subhasisb commented
> @subhasisb ,
> not really. client does a single node stat on all servers and just aggregate the nodes in the receiving end. Jobs do not come into pitcure.

ah yeah i forgot that. so that is not a problem, right

2020-09-04 10:46 UTC, subhasisb commented
code changes are fine. Let's wait till we try out the other approach. We will keep this on hold for now

2021-04-28 06:49 UTC, closed without merging