Parallel requests during stat
subhasisb/openpbs pull request #134
Opened 2020-08-27 16:18 UTC by nithinj

Creating parallel requests during stat as a separate PR.

CC:
@subhasisb ,
@suresh-thelkar

2020-09-04 10:47 UTC, subhasisb approved these changes

2020-09-06 03:47 UTC, suresh-thelkar requested changes
@nithinj, I have few comments. Can you pleas take a look.

2020-09-06 03:47 UTC, suresh-thelkar commented on src/lib/Libifl/int_status.c
> +
@nithinj, As we discussed we also need pbs_verify_attributes_wrapper   to make sure that the attributes get verified from one of the servers that is active if others are down which I am taking care of it in the PR https://github.com/subhasisb/openpbs/pull/135. I think it is better if we this can go after that so that we will have both of these changes. Let me know what do you think.

2020-09-06 03:47 UTC, suresh-thelkar commented on src/lib/Libifl/int_status.c
> +			failed_conn[i] = 1;
I feel it would be better if we can collect pbs_errno also in this array. May be we can make this as array of structures. This is useful when we finally return from this function. And the callers of this function be it scheduler or external clients now actually depending on pbs_errno to proceed further or not. 
qstat display formats are tuned according to the Multi-Server. This information or return code is very much used to display the data in these formats. For more information please look into the PR #135 and also look into the detailed logs that I have attached to see the various print formats.****

2020-09-06 03:47 UTC, suresh-thelkar commented on src/lib/Libifl/int_status.c
> +	for (i = 0; i < get_num_servers(); i++) {
You can collect the value of get_num_servers() and use it. I saw this function getting called more than 1 time in this function.

2020-09-06 03:47 UTC, suresh-thelkar commented on src/lib/Libifl/int_status.c
>  		if (pbs_client_thread_lock_connection(c) != 0)
Do we need to lock for every server instance ? Now that we are having parallel stat requests I think one time locking for all server instances is enough.

2020-09-06 03:47 UTC, suresh-thelkar commented on src/lib/Libifl/pbsD_selectj.c
> +			failed_conn[i] = 1;
Similar changes can be done here.

2020-09-11 16:38 UTC, nithinj commented on src/lib/Libifl/int_status.c
> +
I've rebased with your changes.

2020-09-11 17:04 UTC, nithinj commented on src/lib/Libifl/int_status.c
> +			failed_conn[i] = 1;
I see what you are saying. I believe a better way to handle that is to make ch_errno and ch_errtxt server level than per connection. But if we do that, we need to call set_conn_errno in places where we just set pbs_errno and proceed due to protocol errors. Since the scope of the work is more, can this be addressed when we take it into the mainline?

2020-09-11 18:03 UTC, nithinj commented on src/lib/Libifl/int_status.c
>  		if (pbs_client_thread_lock_connection(c) != 0)
Make sense. 
Since the first real fd and virtual fd are the same, does this put a restriction that the thread who uses the first server is essentially blocking the client from using other connections? @bremanandjk

2020-09-11 18:25 UTC, nithinj commented
@suresh-thelkar 
I've addressed your review comments. Some comments care taken cared as part of rebase so those will be part of older commit.

2020-09-11 20:20 UTC, bremanandjk commented on src/lib/Libifl/int_status.c
>  		if (pbs_client_thread_lock_connection(c) != 0)
Anyway, we don't have a virtual fd concept in this design. 
I am seeing a common lock prior to iterate over all server instances(before the loop). It seems correct for me, this will ensure that one of the multi-thread clients would put the lock before aggregating all servers values.

2020-09-13 03:39 UTC, suresh-thelkar commented on src/lib/Libifl/int_status.c
> +			failed_conn[i] = 1;
I am fine if this can be addressed when we move this code to mainline. Please take a note of it. Since server is single threaded making ch_errno and ch_errtxt server level works.

For the time being can you please make sure that all the print formats etc. done in the PR https://github.com/subhasisb/openpbs/pull/135 are not broken. At least we can set some value for pbs_errno which helps the client to know that the data is partial in case if a one or more servers are down.

2020-09-13 03:54 UTC, suresh-thelkar commented on src/lib/Libifl/int_status.c
>  		if (pbs_client_thread_lock_connection(c) != 0)
Nithin, Are you going to address this ?

2020-09-13 03:57 UTC, suresh-thelkar commented on src/lib/Libifl/int_status.c
>  		if (pbs_client_thread_lock_connection(c) != 0)
Seems this is addressed in latest commit. thanks.

2020-09-13 03:59 UTC, suresh-thelkar reviewed
@nithinj, I just left one comment. Please address that. Apart from this everything looks good to me. I sign off.

2020-09-14 11:21 UTC, nithinj commented on src/lib/Libifl/int_status.c
> +			failed_conn[i] = 1;
I'm not removing any pbs_errno as part of this PR. Whenever connection fails, pbs_errno is set. This is done as part of the invoking functions and hence it is not visible in part changed.

2020-09-14 11:26 UTC, suresh-thelkar commented on src/lib/Libifl/int_status.c
> +			failed_conn[i] = 1;
In this case if it does not affect any of the print formats for qstat/qmgr that we added recently we are good there. Please verify it once.

2020-09-14 11:50 UTC, nithinj commented on src/lib/Libifl/int_status.c
> +			failed_conn[i] = 1;
I've verified the print formats. thanks

2020-09-15 14:26 UTC, subhasisb commented
are we ready to merge this?

2020-09-15 14:40 UTC, nithinj commented
@subhasisb 
This is ready for merging. Suresh has signed-off.

2020-09-15 14:51 UTC, merged